### ISSUE TITLE
Is this compatible with Carbonio CE?

### ISSUE THREAD

**Issue by maicardi** [maldua-suite/zimbra-ose-2fa#17]
I use this extension with my Zimbra 10 FOSS and it solved me a lot of probems, thanks a lot!

I have recently tried Carbonio CE that should be a fork of Zimbra, and even Carbonio CE lacks the 2FA support.

Is zimbra-ose-2fa compatible with Carbonio CE, too?

Thanks a lot.

Marco

**Comment by adriangibanelbtactic** [comment]
> I use this extension with my Zimbra 10 FOSS and it solved me a lot of probems, thanks a lot!

:)
 
> I have recently tried Carbonio CE that should be a fork of Zimbra, and even Carbonio CE lacks the 2FA support.

Carbonio CE being a fork of Zimbra is subject to debate XD .

> Is zimbra-ose-2fa compatible with Carbonio CE, too?

zimbra-ose-2fa has not been developed with Carbonio CE in mind.

If Carbonio CE's zm-mailbox is similar enough to Zimbra's zm-mailbox it might work, yes, but this would be something that you need to test in depth in a VM to check what works and what doesn't work.

So... the answer is... I have no idea.

In any case Carbonio CE won't be supported officially by this project (that would be much more work than expected).
