### ISSUE TITLE
Problem installing zimbra-ose-2fa

### ISSUE THREAD

**Issue by bilbolodz** [maldua-suite/zimbra-ose-2fa#18]
I'm trying to use zimbra-ose-2fa with self compiled Zimbra version: 10.0.6.GA.0423 FOSS.
I've used "Automatic installation" which run smoothly without any errors but I can't find additional elements in User or COS section of admin interface.
In "Admin extensions" section I can see:
![obraz](https://github.com/maldua-suite/zimbra-ose-2fa/assets/4696144/ee53d47a-96d6-4e50-b807-c572321ea5a6)

but NOT in Zimlets section.

I've tried zmzimletctl listZimlets command and I can see:
```
Installed Zimlet files on this host:
	com_btactic_twofactorauth_admin
```
but  it's NOT listed in "Installed Zimlets in LDAP" or "Available Zimlets in COS" sections.

Any idea what could be wrong?

**Comment by adriangibanelbtactic** [comment]
> I'm trying to use zimbra-ose-2fa with self compiled Zimbra version: 10.0.6.GA.0423 FOSS.

Your installation seems to be a custom built tgz based on the ianw1974 zimbra-build-scripts. Isn't it?

That's a moving target which I cannot support.

Right now **develop branches** (and even 10.1.0 tag) have had some 2FA stuff updated recently which I don't support.
So I am afraid I cannot support ianw1974 zimbra-build-scripts builds done after, let's say, 2024 02.

Documentation says that support versions are:
- Zimbra 10.0.x
- Zimbra 9.x
- Zimbra 8.8.15
for a reason.

If you build 10.0.6 thanks to ianw1974 zimbra-build-scripts you're not getting a Zimbra 10.0.x build, it's something else which I name myself as not 'Zimbra' but 'Zimbra Next'.

I might end up updating that _Supported Zimbra versions_ section stating that support versions need to be built from tags (not develop branches).

**Comment by adriangibanelbtactic** [comment]
Explanation was given.
Feedback was not received in a long time.

Closing the ticket.

**Comment by bilbolodz** [comment]
Just for information: I've installed 10.1.1 from https://github.com/ianw1974/zimbra-build-scripts build and 2fa is working fine.

**Comment by alejandro-chirva** [comment]
> Just for information: I've installed 10.1.1 from https://github.com/ianw1974/zimbra-build-scripts build and 2fa is working fine.
What OS did you use?

**Comment by adriangibanelbtactic** [comment]
> Just for information: I've installed 10.1.1 from https://github.com/ianw1974/zimbra-build-scripts build and 2fa is working fine.

That's hard to believe.

- Was it a custom build or did you download a tgz from him?
- Can you please share with us the tgz filename?
- Is it an installation from scratch or have you done an update?
- What 2FA features have you actually tried?

Thank you for your feedback.

**Comment by bilbolodz** [comment]
>     Was it a custom build or did you download a tgz from him?
He offer only environment for building own packages not tgz so "it was custom build"

> Can you please share with us the tgz filename?
If you are interested I can upload somewhere my tgz

>     Is it an installation from scratch or have you done an update?
It was update made on production server

>     What 2FA features have you actually tried?
I thing "all that 2fa offers"

**Comment by adriangibanelbtactic** [comment]
> > ```
> > Was it a custom build or did you download a tgz from him?
> > ```
> 
> He offer only environment for building own packages not tgz so "it was custom build"

He actually has a [download page](https://techfiles.online/zimbra/).

> > Can you please share with us the tgz filename?

> If you are interested I can upload somewhere my tgz

The tgz filename is good enough. I am interested on the version you try to build and the date when you built it.

> > ```
> > Is it an installation from scratch or have you done an update?
> > ```
> 
> It was update made on production server

And you updated from which old version exactly?

> > ```
> > What 2FA features have you actually tried?
> > ```
> 
> I thing "all that 2fa offers"

That's still strange that you don't get that **Two factor code could not be initialized** on the login page that it's shown at https://github.com/maldua-suite/zimbra-ose-2fa/issues/20#issue-2616033674 .
Did you maybe change the login page so that it showed the classic login?
